platform :ios, '8.0'
use_frameworks!

target 'TestPods_Example' do
  pod 'TestPods', :path => '../'

  target 'TestPods_Tests' do
      inherit! :search_paths
      pod 'TestPods', :path => '../'
  end
end
